name: "on push"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main

concurrency: "on_push-${{ github.ref_name }}"

jobs:
  _1795b36b-bd83-4ed0-94a3-282eeb8d4693:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_ProjectTimelineProjections/.github/workflows/validate_with_dependencies.yaml@CI-v1
    with:
      repo_branch: ${{ github.ref_name }}

  _676ef578-d3e3-4908-9df4-9107ded3e9b5:
    name: "Promote"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_promote.yaml@CI-v1

    needs:
      - _1795b36b-bd83-4ed0-94a3-282eeb8d4693
