# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/manual_validate.jinja2.yaml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

name: "Validate"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      force_setup:                          {type: boolean, required: false, default: false, description: "Apply the '--force' flag during setup activities."}
      force_activate:                       {type: boolean, required: false, default: false, description: "Apply the '--force' flag during activation activities."}
      no_cache:                             {type: boolean, required: false, default: false, description: "Do not use the GitHub action cache for this build."}

jobs:
  _ea68282e-cf98-434e-976b-e7698857c891:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_ProjectTimelineProjections/.github/workflows/validate.yaml@CI-v1
    with:
      repo_branch: ${{ github.ref_name }}

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}
